wrong port/address in debug log
awslabs/amazon-kinesis-video-streams-webrtc-sdk-c pull request #1495
Opened 2022-06-14 00:40 UTC by zhuker

*Issue #, if available:*
in master debug log prints
```
iceCandidatePairCheckConnection(): remote ip:192.168.254.75, port:192, local ip:49360.168.1.130, port:192
```
notice port is `192` while local ip starts with `49360`

*Description of changes:*

prints as expected
```
iceCandidatePairCheckConnection(): remote ip:192.168.254.75, port:49360, local ip:192.168.1.130, port:39362
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-06-15 15:15 UTC, vc60er approved these changes

2022-06-15 16:32 UTC, MushMal approved these changes

2022-06-15 16:36 UTC, niyatim23 requested changes
Hi, thank you for the PR. Can you please change the base branch from `master` to `develop` as we accept contributions in that branch

2022-07-28 16:59 UTC, disa6302 commented
@zhuker ,

Thank you! Can you direct this PR to the develop branch instead?

2023-02-14 17:07 UTC, niyatim23 commented
Closing in favor of https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1642#

2023-02-14 17:07 UTC, closed without merging