fix turn allocation taken long time when credential is incorrect
awslabs/amazon-kinesis-video-streams-webrtc-sdk-c pull request #1536
Opened 2022-08-17 08:11 UTC by vc60er

*Issue #, if available:*
turn allocation taken long time when credential is incorrect. It taken about 10s+ until the local candidate gathering timeout

*Description of changes:*
1. add trunStateFailedFn, called when turn state change to TURN_STATE_FAILED, and then update pNewCandidate state from ICE_CANDIDATE_STATE_NEW to ICE_CANDIDATE_STATE_INVALID
2. add stateTryCountMax and stateTryCount, limit the allocation times not more than stateTryCountMax

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-17 16:48 UTC, MushMal reviewed
A few minor comments. The idea is solid otherwise.

I wish this was covered in unit tests.

2022-08-17 16:48 UTC, MushMal commented on src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
> +#define STATUS_TURN_CONNECTION_FAILED_TO_ALLOCATION                        STATUS_ICE_BASE + 0x0000002a
Recommend renaming to STATUS_TURN_CONNECTION_ALLOCAITON_FAILED

2022-08-17 16:48 UTC, MushMal commented on src/source/Ice/IceAgent.c
> +STATUS trunStateFailedFn(UINT64 data, PSocketConnection pSocketConnection) {
It's a good idea to include the pSocketConnection even if it's not used right now. Two recommendations:

1) Make this as the first parameter
2) Add UNUSED_PARAM(pSocketConnection) to fix unused param warning

2022-08-17 16:48 UTC, MushMal commented on src/source/Ice/IceAgent.c
> +    return 0;
Return STATUS_SUCCESS

2022-08-17 16:48 UTC, MushMal commented on src/source/Ice/IceAgent.c
> +    return 0;
Actually, you can decorate the function like many others in the file where it checks for pNewCandidate not being null like this

CHK(pNewCandidate != NULL, STATUS_NULL_ARG);

You will need to add a CleanUp: label at the end and STATUS retStatus = STATUS_SUCCESS at the beginning

2022-08-17 16:48 UTC, MushMal commented on src/source/Ice/TurnConnection.c
> +            break;
WOW. This seems to have been a bug in the code for a whlie.

2022-08-17 16:48 UTC, MushMal commented on src/source/Ice/TurnConnection.h
> +#define DEFAULT_TURN_ALLOCATION_MAX_TRY_COUNT             3
I wonder if folks from AWS can comment on the choice of the default max retry count being 3. It seems to be a good candidate.

2022-08-18 18:10 UTC, MushMal approved these changes

2022-09-14 19:11 UTC, MushMal approved these changes
Nice!

2022-10-17 22:24 UTC, jdelapla requested changes

2022-10-17 22:24 UTC, jdelapla commented on src/source/Ice/IceAgent.c
> +STATUS trunStateFailedFn(PSocketConnection pSocketConnection, UINT64 data) {
nit, typo. trun -> turn

2022-10-17 22:24 UTC, jdelapla commented on src/source/Ice/IceAgent.c
> +    callback.turnStateFailedFn= trunStateFailedFn;
typo again

2023-02-16 03:43 UTC, sirknightj commented
Hi @vc60er thanks for your contribution. Could you please rebase to latest `develop` branch so we can get this merged in?

2023-03-17 19:28 UTC, niyatim23 commented
Closing since the PR with the fixed CI has been merged. Thanks for your contribution

2023-03-17 19:28 UTC, closed without merging