Introducing profiling of code sections and APIs
awslabs/amazon-kinesis-video-streams-webrtc-sdk-c pull request #1755
Opened 2023-07-20 00:50 UTC by disa6302

What was changed?

- Samples were cleaned up to use CHK_X and DLOGx instead of `printfs` and `if...else`. This helps in code readability
- Enabling profile level file logs to be generated by default
- New structures to store latency calculations across peer connection, ICE and signaling
- Some logging improvements and fixes

Why was it changed?

- Customers do not have a way to clearly understand what contributes to the latency to send out the first frame. Having a separate log file helps in visualizing the different components contributing to send out the first frame and it can also be a way for users to share the data with us when reaching out about latency issues
- New fields were added into stats and new APIs to pull the data was added to allow monitoring these across runs and visualize them graphically if needed
- Made some logging improvements to prevent misleading error vs normal warn logs which are necessarily not cause for failure
- Cleaned up samples since it was not readable and added some modularization to make it easier for first time users.

How it was changed?

- Added new APIs to profile different sections of the code: `PROFILE_CALL`, `PROFILE_CALL_WITH_T_OBJ`, `PROFILE_WITH_START_TIME`, `PROFILE_WITH_START_TIME_OBJ`
- Enabled profile level log file generation by default in samples. Other level log files can be generated by running `export AWS_ENABLE_FILE_LOGGING=TRUE`
- Added new APIs to read latency values: `getPeerConnectionMetrics`, `getIceAgentMetrics`

Changes in upcoming PRs:

- TURN related latency measurements
- Have a better way to extract `closePeerConnection` and `freePeerConnection` time taken. Right now, these metrics being passed to the application make no sense because these metrics would be calculate while freeing the peer connection object this is part of. 

Testing:

- File logging APIs were tested as part of the PIC unit tests
- Normal runs and ensuring the relevant log files are created

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-07-20 00:51 UTC, disa6302 commented on CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
> +    GIT_TAG           add-new-log-level
Need to change to a specific commit once this PR passes CI: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/pull/379

2023-07-28 19:58 UTC, jdelapla requested changes
Alright, still going through ICE/Peer/Signaling but wanted to give you a head start on the requested macro changes.

2023-07-28 19:58 UTC, jdelapla commented on src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
> +        UINT64 startTime = GETTIME();                                                                                                                \
Variable declaration in a macro like this means the variable can't be declared at top of function, which is troublesome for some C compilers.

Our other macros like this one that rely on `retStatus` come with the requirement that the variable be declared outside the scope of this macro.

2023-07-28 19:58 UTC, jdelapla commented on src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
> +        DLOGP("[%s] Time taken: %" PRIu64 " ms", msg, t);                                                                                            \
put parenthesis around `msg`, since it's always a right-side argument.

2023-07-28 19:58 UTC, jdelapla commented on src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
> +        DLOGP("[%s] Time taken: %" PRIu64 " ms", msg, (GETTIME() - startTime) / HUNDREDS_OF_NANOS_IN_A_MILLISECOND);                                 \
parenthesis around msg.

2023-07-28 19:58 UTC, jdelapla commented on src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
> +        t2 = (GETTIME() - t1) / HUNDREDS_OF_NANOS_IN_A_MILLISECOND;                                                                                  \
parenthesis around t1 since it's always a right side parameter.

2023-07-28 19:58 UTC, jdelapla commented on src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
> +        DLOGP("[%s] Time taken: %" PRIu64 " ms", msg, t2);                                                                                           \
and msg again.

2023-07-28 19:58 UTC, jdelapla commented on src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
> +        UINT64 startTime = GETTIME();                                                                                                                \
We could also rename it to show that it's a variable for this macro.

2023-07-31 20:09 UTC, jdelapla approved these changes

2023-07-31 21:23 UTC, jdelapla approved these changes

2023-07-31 21:23 UTC, merged